/*
 * This file was automatically generated by EvoSuite
 * Thu May 21 12:59:51 GMT 2026
 */

package order;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.LinkedList;
import java.util.List;
import order.CheckoutCalculator;
import order.CheckoutRequest;
import order.CheckoutResult;
import order.Coupon;
import order.CouponPolicy;
import order.CouponType;
import order.CustomerProfile;
import order.CustomerTier;
import order.OrderItem;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.time.MockLocalDate;

public class CheckoutCalculator_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CouponPolicy couponPolicy0 = new CouponPolicy();
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator(couponPolicy0);
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.VIP;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 4, false, "subtotal");
      CouponType couponType0 = CouponType.PERCENT;
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      LocalDate localDate0 = MockLocalDate.ofEpochDay(4);
      Coupon coupon0 = new Coupon("subtotal", couponType0, bigDecimal0, bigDecimal0, localDate0, false, false);
      CheckoutRequest checkoutRequest0 = mock(CheckoutRequest.class, new ViolatedAssumptionAnswer());
      doReturn(coupon0).when(checkoutRequest0).getCoupon();
      doReturn(customerProfile0, customerProfile0, (CustomerProfile) null).when(checkoutRequest0).getCustomer();
      doReturn(linkedList0, linkedList0).when(checkoutRequest0).getItems();
      // Undeclared exception!
      try { 
        checkoutCalculator0.checkout(checkoutRequest0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.VIP;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 18, false, "uJJm");
      CouponType couponType0 = CouponType.PERCENT;
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      LocalDate localDate0 = MockLocalDate.now();
      Coupon coupon0 = new Coupon("uJJm", couponType0, bigDecimal0, bigDecimal0, localDate0, false, false);
      OrderItem orderItem0 = new OrderItem("uJJm", 18, bigDecimal0, false, "uJJm");
      linkedList0.add(orderItem0);
      CheckoutRequest checkoutRequest0 = new CheckoutRequest(linkedList0, customerProfile0, coupon0, true);
      CheckoutResult checkoutResult0 = checkoutCalculator0.checkout(checkoutRequest0, localDate0);
      assertFalse(checkoutResult0.isCouponApplied());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.VIP;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 18, false, "bJJm");
      CouponType couponType0 = CouponType.FREE_SHIPPING;
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      LocalDate localDate0 = MockLocalDate.ofYearDay(18, 18);
      Coupon coupon0 = new Coupon("bJJm", couponType0, bigDecimal0, bigDecimal0, localDate0, false, false);
      OrderItem orderItem0 = new OrderItem("bJJm", 18, bigDecimal0, false, "bJJm");
      linkedList0.add(orderItem0);
      CheckoutRequest checkoutRequest0 = new CheckoutRequest(linkedList0, customerProfile0, coupon0, true);
      CheckoutResult checkoutResult0 = checkoutCalculator0.checkout(checkoutRequest0, localDate0);
      assertTrue(checkoutResult0.isCouponApplied());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      CustomerTier customerTier0 = CustomerTier.MEMBER;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 4, true, "xMX4P]Sa<?c'6");
      BigDecimal bigDecimal0 = new BigDecimal((-326));
      // Undeclared exception!
      try { 
        checkoutCalculator0.tierDiscount(customerProfile0, bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // subtotal must be non-negative
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      CustomerTier customerTier0 = CustomerTier.MEMBER;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 2220, false, "minimumSubtotal");
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      BigDecimal bigDecimal1 = checkoutCalculator0.tierDiscount(customerProfile0, bigDecimal0);
      assertEquals((byte)0, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.MEMBER;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 13, false, "INTL");
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      CouponType couponType0 = CouponType.FIXED;
      Coupon coupon0 = new Coupon("INTL", couponType0, bigDecimal0, bigDecimal0, localDate0, false, false);
      OrderItem orderItem0 = new OrderItem(">=0", 13, bigDecimal0, false, "3.1W5");
      linkedList0.add(orderItem0);
      CheckoutRequest checkoutRequest0 = new CheckoutRequest(linkedList0, customerProfile0, coupon0, true);
      CheckoutResult checkoutResult0 = checkoutCalculator0.checkout(checkoutRequest0, localDate0);
      assertTrue(checkoutResult0.isCouponApplied());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.VIP;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 3, false, "bJJm");
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      LocalDate localDate0 = MockLocalDate.of(3, 3, 3);
      OrderItem orderItem0 = new OrderItem("bJJm", 3, bigDecimal0, false, "bJJm");
      linkedList0.add(orderItem0);
      CheckoutRequest checkoutRequest0 = new CheckoutRequest(linkedList0, customerProfile0, (Coupon) null, false);
      CheckoutResult checkoutResult0 = checkoutCalculator0.checkout(checkoutRequest0, localDate0);
      assertFalse(checkoutResult0.isCouponApplied());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.GUEST;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 3, false, "INTL");
      BigDecimal bigDecimal0 = new BigDecimal(3);
      LocalDate localDate0 = MockLocalDate.of(3, 3, 3);
      OrderItem orderItem0 = new OrderItem("INTL", 3, bigDecimal0, false, "INTL");
      linkedList0.add(orderItem0);
      CheckoutRequest checkoutRequest0 = new CheckoutRequest(linkedList0, customerProfile0, (Coupon) null, false);
      CheckoutResult checkoutResult0 = checkoutCalculator0.checkout(checkoutRequest0, localDate0);
      assertFalse(checkoutResult0.isCouponApplied());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.GUEST;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 3, true, "EU");
      CouponType couponType0 = CouponType.FIXED;
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      LocalDate localDate0 = MockLocalDate.of(3, 3, 3);
      Coupon coupon0 = new Coupon("EU", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      OrderItem orderItem0 = new OrderItem("EU", 3, bigDecimal0, true, "EU");
      linkedList0.add(orderItem0);
      CheckoutRequest checkoutRequest0 = new CheckoutRequest(linkedList0, customerProfile0, coupon0, true);
      CheckoutResult checkoutResult0 = checkoutCalculator0.checkout(checkoutRequest0, localDate0);
      assertTrue(checkoutResult0.isCouponApplied());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.VIP;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 4, false, (String) null);
      BigDecimal bigDecimal0 = new BigDecimal(4);
      LocalDate localDate0 = MockLocalDate.now();
      OrderItem orderItem0 = new OrderItem("uJ", 4, bigDecimal0, true, "uJ");
      linkedList0.add(orderItem0);
      CouponType couponType0 = CouponType.FIXED;
      Coupon coupon0 = new Coupon("uJ", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      CheckoutRequest checkoutRequest0 = new CheckoutRequest(linkedList0, customerProfile0, coupon0, true);
      CheckoutResult checkoutResult0 = checkoutCalculator0.checkout(checkoutRequest0, localDate0);
      assertFalse(checkoutResult0.isCouponApplied());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      CustomerTier customerTier0 = CustomerTier.MEMBER;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 0, true, "5");
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      BigDecimal bigDecimal1 = checkoutCalculator0.tierDiscount(customerProfile0, bigDecimal0);
      assertEquals((byte)0, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = null;
      try {
        checkoutCalculator0 = new CheckoutCalculator((CouponPolicy) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // couponPolicy
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      // Undeclared exception!
      try { 
        checkoutCalculator0.tierDiscount((CustomerProfile) null, bigDecimal0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // customer
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.VIP;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 5336, false, "uJJoma");
      CouponType couponType0 = CouponType.PERCENT;
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      LocalDate localDate0 = MockLocalDate.now();
      Coupon coupon0 = new Coupon(",q", couponType0, bigDecimal0, bigDecimal0, localDate0, true, false);
      OrderItem orderItem0 = new OrderItem("uJJoma", 5336, bigDecimal0, false, "uJJoma");
      linkedList0.add(orderItem0);
      CheckoutRequest checkoutRequest0 = new CheckoutRequest(linkedList0, customerProfile0, coupon0, true);
      BigDecimal bigDecimal1 = checkoutCalculator0.subtotal(checkoutRequest0);
      assertEquals((short)5336, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CouponPolicy couponPolicy0 = new CouponPolicy();
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator(couponPolicy0);
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.GUEST;
      boolean boolean0 = true;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 1572, true, (String) null);
      String string0 = "";
      CouponType couponType0 = CouponType.FIXED;
      CheckoutRequest checkoutRequest0 = mock(CheckoutRequest.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(checkoutRequest0).getItems();
      // Undeclared exception!
      try { 
        checkoutCalculator0.subtotal(checkoutRequest0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.GUEST;
      BigDecimal bigDecimal0 = new BigDecimal((double) 1572);
      OrderItem orderItem0 = new OrderItem("1}F)\"]*/BrvJ,j]7", 1572, bigDecimal0, false, "1}F)\"]*/BrvJ,j]7");
      linkedList0.add(orderItem0);
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 1572, true, (String) null);
      CheckoutRequest checkoutRequest0 = new CheckoutRequest(linkedList0, customerProfile0, (Coupon) null, false);
      BigDecimal bigDecimal1 = checkoutCalculator0.subtotal(checkoutRequest0);
      assertEquals((short) (-19184), bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      CustomerTier customerTier0 = CustomerTier.VIP;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 1342, false, "rc~&$[!*?EVV");
      BigDecimal bigDecimal1 = checkoutCalculator0.tierDiscount(customerProfile0, bigDecimal0);
      assertEquals((byte)1, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CheckoutCalculator checkoutCalculator0 = new CheckoutCalculator();
      LinkedList<OrderItem> linkedList0 = new LinkedList<OrderItem>();
      CustomerTier customerTier0 = CustomerTier.GUEST;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 18, false, "uJJm");
      CouponType couponType0 = CouponType.PERCENT;
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      Coupon coupon0 = new Coupon("uJJm", couponType0, bigDecimal0, bigDecimal0, localDate0, false, false);
      OrderItem orderItem0 = new OrderItem("uJJm", 18, bigDecimal0, false, "uJJm");
      linkedList0.add(orderItem0);
      CheckoutRequest checkoutRequest0 = new CheckoutRequest(linkedList0, customerProfile0, coupon0, true);
      CheckoutResult checkoutResult0 = checkoutCalculator0.checkout(checkoutRequest0, localDate0);
      assertTrue(checkoutResult0.isCouponApplied());
  }
}
