/*
 * This file was automatically generated by EvoSuite
 * Thu May 21 13:01:05 GMT 2026
 */

package order;

import org.junit.Test;
import static org.junit.Assert.*;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.MathContext;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZoneOffset;
import order.Coupon;
import order.CouponPolicy;
import order.CouponType;
import order.CustomerProfile;
import order.CustomerTier;
import org.evosuite.runtime.mock.java.time.MockLocalDate;

public class CouponPolicy_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      LocalDate localDate0 = MockLocalDate.of(2023, 1, 1);
      CouponType couponType0 = CouponType.PERCENT;
      Coupon coupon0 = new Coupon("RuhwXK`3US", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      CustomerTier customerTier0 = CustomerTier.GUEST;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 2, true, "RuhwXK`3US");
      CouponPolicy couponPolicy0 = new CouponPolicy();
      boolean boolean0 = couponPolicy0.isApplicable(coupon0, customerProfile0, bigDecimal0, localDate0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      LocalDate localDate0 = MockLocalDate.now();
      CouponPolicy couponPolicy0 = new CouponPolicy();
      boolean boolean0 = couponPolicy0.isApplicable((Coupon) null, (CustomerProfile) null, bigDecimal0, localDate0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      LocalDate localDate0 = MockLocalDate.now();
      CouponType couponType0 = CouponType.PERCENT;
      Coupon coupon0 = new Coupon("RuhwXK`3US", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      CustomerTier customerTier0 = CustomerTier.GUEST;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 2, true, "RuhwXK`3US");
      CouponPolicy couponPolicy0 = new CouponPolicy();
      BigDecimal bigDecimal1 = new BigDecimal((-2139.32866748));
      // Undeclared exception!
      try { 
        couponPolicy0.isApplicable(coupon0, customerProfile0, bigDecimal1, localDate0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // subtotal must be non-negative
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      CouponType couponType0 = CouponType.PERCENT;
      Coupon coupon0 = new Coupon("T)Q5Ur7ji))", couponType0, bigDecimal0, bigDecimal0, localDate0, false, false);
      CustomerTier customerTier0 = CustomerTier.MEMBER;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 6, false, "T)Q5Ur7ji))");
      CouponPolicy couponPolicy0 = new CouponPolicy();
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutesSeconds(6, 6, 6);
      LocalDate localDate1 = MockLocalDate.of(2023, 1, 2);
      String string0 = couponPolicy0.rejectionReason(coupon0, customerProfile0, bigDecimal0, localDate1);
      assertEquals("EXPIRED", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      CouponType couponType0 = CouponType.FIXED;
      Coupon coupon0 = new Coupon("MINIMUM_NOT_REACHED", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      CustomerTier customerTier0 = CustomerTier.MEMBER;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 2, true, "MINIMUM_NOT_REACHED");
      CouponPolicy couponPolicy0 = new CouponPolicy();
      BigDecimal bigDecimal1 = BigDecimal.ZERO;
      String string0 = couponPolicy0.rejectionReason(coupon0, customerProfile0, bigDecimal1, localDate0);
      assertEquals("MINIMUM_NOT_REACHED", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CouponType couponType0 = CouponType.PERCENT;
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      Coupon coupon0 = new Coupon("amount", couponType0, bigDecimal0, bigDecimal0, localDate0, false, false);
      CustomerTier customerTier0 = CustomerTier.MEMBER;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 1017, false, "amount");
      CouponPolicy couponPolicy0 = new CouponPolicy();
      String string0 = couponPolicy0.rejectionReason(coupon0, customerProfile0, bigDecimal0, localDate0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      CouponType couponType0 = CouponType.PERCENT;
      Coupon coupon0 = new Coupon("MINIMUM_NOT_REACHED", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      CustomerTier customerTier0 = CustomerTier.VIP;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 2, false, "MINIMUM_NOT_REACHED");
      CouponPolicy couponPolicy0 = new CouponPolicy();
      String string0 = couponPolicy0.rejectionReason(coupon0, customerProfile0, bigDecimal0, localDate0);
      assertEquals("FIRST_ORDER_ONLY", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CouponType couponType0 = CouponType.FIXED;
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      Coupon coupon0 = new Coupon("amount", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      CustomerTier customerTier0 = CustomerTier.MEMBER;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 1008, true, "amount");
      CouponPolicy couponPolicy0 = new CouponPolicy();
      String string0 = couponPolicy0.rejectionReason(coupon0, customerProfile0, bigDecimal0, localDate0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CouponPolicy couponPolicy0 = new CouponPolicy();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      BigDecimal bigDecimal1 = couponPolicy0.discountFor((Coupon) null, bigDecimal0);
      assertEquals((short)0, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      CouponType couponType0 = CouponType.PERCENT;
      CouponPolicy couponPolicy0 = new CouponPolicy();
      Coupon coupon0 = new Coupon("D.#fe.=oJV'\"e~cATb", couponType0, bigDecimal0, bigDecimal0, localDate0, false, false);
      BigDecimal bigDecimal1 = new BigDecimal((-3208L));
      // Undeclared exception!
      try { 
        couponPolicy0.discountFor(coupon0, bigDecimal1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // subtotal must be non-negative
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CouponPolicy couponPolicy0 = new CouponPolicy();
      CouponType couponType0 = CouponType.FREE_SHIPPING;
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      LocalDate localDate0 = MockLocalDate.now();
      Coupon coupon0 = new Coupon("&_(mtY=NI @6&T;Qc9A", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      BigDecimal bigDecimal1 = couponPolicy0.discountFor(coupon0, bigDecimal0);
      assertNotSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CouponPolicy couponPolicy0 = new CouponPolicy();
      CouponType couponType0 = CouponType.FIXED;
      BigDecimal bigDecimal0 = new BigDecimal(1000);
      LocalDate localDate0 = MockLocalDate.ofYearDay(3, 3);
      Coupon coupon0 = new Coupon("amount", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      BigDecimal bigDecimal1 = couponPolicy0.discountFor(coupon0, bigDecimal0);
      assertFalse(bigDecimal1.equals((Object)bigDecimal0));
      assertEquals((short)1000, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CouponPolicy couponPolicy0 = new CouponPolicy();
      BigDecimal bigDecimal0 = new BigDecimal(1000);
      LocalDate localDate0 = MockLocalDate.ofYearDay(3, 3);
      CustomerTier customerTier0 = CustomerTier.MEMBER;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 0, true, "amount");
      String string0 = couponPolicy0.rejectionReason((Coupon) null, customerProfile0, bigDecimal0, localDate0);
      assertEquals("NO_COUPON", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CouponType couponType0 = CouponType.PERCENT;
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      Coupon coupon0 = new Coupon("amount", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      CustomerTier customerTier0 = CustomerTier.MEMBER;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 1008, true, "amount");
      CouponPolicy couponPolicy0 = new CouponPolicy();
      BigDecimal bigDecimal1 = new BigDecimal((-1610.1109194097833));
      // Undeclared exception!
      try { 
        couponPolicy0.rejectionReason(coupon0, customerProfile0, bigDecimal1, localDate0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // subtotal must be non-negative
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CouponPolicy couponPolicy0 = new CouponPolicy();
      CouponType couponType0 = CouponType.FREE_SHIPPING;
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Coupon coupon0 = new Coupon("m", couponType0, bigDecimal0, bigDecimal0, localDate0, false, false);
      // Undeclared exception!
      try { 
        couponPolicy0.discountFor(coupon0, (BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // subtotal
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      CouponType couponType0 = CouponType.FIXED;
      Coupon coupon0 = new Coupon("amount", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      CouponPolicy couponPolicy0 = new CouponPolicy();
      // Undeclared exception!
      try { 
        couponPolicy0.isApplicable(coupon0, (CustomerProfile) null, bigDecimal0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // customer
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      CouponType couponType0 = CouponType.PERCENT;
      Coupon coupon0 = new Coupon("INIMU9_NT_RAHHE", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      CouponPolicy couponPolicy0 = new CouponPolicy();
      // Undeclared exception!
      try { 
        couponPolicy0.rejectionReason(coupon0, (CustomerProfile) null, bigDecimal0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // customer
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      LocalDate localDate0 = MockLocalDate.now();
      CouponType couponType0 = CouponType.FIXED;
      Coupon coupon0 = new Coupon("amount", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      CouponPolicy couponPolicy0 = new CouponPolicy();
      BigDecimal bigDecimal1 = couponPolicy0.discountFor(coupon0, bigDecimal0);
      assertNotSame(bigDecimal1, bigDecimal0);
      assertEquals((short)10, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      LocalDate localDate0 = MockLocalDate.now();
      CouponType couponType0 = CouponType.PERCENT;
      Coupon coupon0 = new Coupon("q/le?GSh~;", couponType0, bigDecimal0, bigDecimal0, localDate0, true, true);
      CouponPolicy couponPolicy0 = new CouponPolicy();
      byte[] byteArray0 = new byte[9];
      byteArray0[0] = (byte)119;
      byteArray0[1] = (byte) (-122);
      byteArray0[4] = (byte) (-24);
      BigInteger bigInteger0 = new BigInteger(byteArray0);
      MathContext mathContext0 = MathContext.DECIMAL64;
      BigDecimal bigDecimal1 = new BigDecimal(bigInteger0, 0, mathContext0);
      BigDecimal bigDecimal2 = couponPolicy0.discountFor(coupon0, bigDecimal1);
      assertEquals((byte)112, bigDecimal2.byteValue());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CouponPolicy couponPolicy0 = new CouponPolicy();
      CouponType couponType0 = CouponType.FIXED;
      BigDecimal bigDecimal0 = new BigDecimal(3);
      LocalDate localDate0 = MockLocalDate.of(3, 3, 3);
      CustomerTier customerTier0 = CustomerTier.VIP;
      CustomerProfile customerProfile0 = new CustomerProfile(customerTier0, 3, false, "amount");
      Coupon coupon0 = new Coupon("amount", couponType0, bigDecimal0, bigDecimal0, localDate0, false, false);
      BigDecimal bigDecimal1 = BigDecimal.TEN;
      String string0 = couponPolicy0.rejectionReason(coupon0, customerProfile0, bigDecimal1, localDate0);
      assertEquals("", string0);
  }
}
